### ISSUE TITLE
Unable to work with MBAMService.exe

### ISSUE THREAD

**Issue by don-dolarson** [kadrim/PrimoCacheBackupDetect#7]
This is weird. I'm trying with a process of Malwarebytes which is MBAMService.exe and they can't work with each other. I'm getting an error message when right-clicking on taskbar > check process, like the one on the attached screenshot. When the name has been changed to just MBAM.exe then it gave no errors.
![ASDF](https://user-images.githubusercontent.com/49354563/93388451-065a6d00-f86b-11ea-88f8-d47adb6a7088.jpg)

**Comment by kadrim** [comment]
Thanks for your message.

can you please post your current .ini file?

also, please try to start the application via right click and then "run as administrator". I think we have an issue here with UAC.

**Comment by don-dolarson** [comment]
This is my .ini file code:
```
[Config]
Interval=60000
Process=MBAMService.exe
Threshold=50000000
PauseCmd="C:\Program Files\PrimoCache\rxpcc.exe" pause -s -a
ResumeCmd="C:\Program Files\PrimoCache\rxpcc.exe" resume -s -a
```

The application ask for UAC whenever it starts. I've downloaded a new copy of PrimoCacheBackupDetect, and even compiled the open source code and it looks the same in both. Now it looks like on the attached screenshot, though.
![BackupDetect](https://user-images.githubusercontent.com/49354563/93652005-c97daa00-fa13-11ea-9c9d-08a81702f282.jpg)

**Comment by kadrim** [comment]
That is rather strange. So you are note able to repoduce the first error mentioned above?
the second one ssems to be related to an issue loading the .ini files.

Are you running multiple instances?

**Comment by kadrim** [comment]
but as you are able to compile the scripts yourself we will find a solution much more easily :-)

**Comment by don-dolarson** [comment]
Nope, running only 1 instance, and no, I'm not able to reproduce. Tell me what to do so I can help to solve the problem.

**Comment by kadrim** [comment]
so your current state is really another issue here. Your ini file won't read. That should never happen.

The term "backupService-ab.exe" is hard-coded only in one place and that's where it tries to set default values if no ini file can be found.

The ini file itself is read via:

```au3
Global Const $configFile = @ScriptDir & "\PrimoCacheBackupDetect.ini"
```
if the file can be read, there should never be a reference to "backupService-ab.exe".

So is your ini file really called "PrimoCacheBackupDetect.ini" and resides in the same directory as the .exe file?
Please double check

**Comment by don-dolarson** [comment]
Yes, it is, and as told before, when changing MBAMService.exe to anything else, it works as intended.

**Comment by kadrim** [comment]
that is really strange.

could you please compile the attached script and run it alongside the mentioned .ini file?


[PrimoCacheBackupDetect.zip](https://github.com/kadrim/PrimoCacheBackupDetect/files/5267947/PrimoCacheBackupDetect.zip)

it should output this:

![image](https://user-images.githubusercontent.com/8304331/94009457-c7fe0a00-fda4-11ea-92a3-a3b992fb3140.png)

also please do upload your ini file (not just the contents) here, maybe we have some weird bugs with utf8 files or something like this.

**Comment by don-dolarson** [comment]
I've just tested it a little bit more and when **any** other process is specified in the .ini file, for example, _aquasuite.exe, AquaComputerService.exe, Photoshop.exe, Autoruns64.exe_, I'm getting something like on the attached picture, and the taskbar icon of PrimoCacheBackupDetect is then changing to the yellow icon with an exclamation mark.
![1](https://user-images.githubusercontent.com/49354563/94010422-342d3d80-fda6-11ea-9e04-730683b26d9d.png)
![2](https://user-images.githubusercontent.com/49354563/94010429-37282e00-fda6-11ea-8d99-a3ca833b755d.png)
![3](https://user-images.githubusercontent.com/49354563/94010433-37c0c480-fda6-11ea-9549-dda0261a2ae2.png)

**Comment by kadrim** [comment]
hmm this seems alright.

what is it with the mbamservice.exe then? did you run the new script already? we will adjust the settings together to find the problem.

**Comment by kadrim** [comment]
also, could you check with which user this process runs on your computer?

**Comment by don-dolarson** [comment]
That's right. I'm getting the same output as you in the attached picture.
[PrimoCacheBackupDetect.zip](https://github.com/kadrim/PrimoCacheBackupDetect/files/5268002/PrimoCacheBackupDetect.zip)

**Comment by don-dolarson** [comment]
I'm the only user on this machine.

**Comment by kadrim** [comment]
> I'm the only user on this machine.

could you please double check with the taskmanager? i am also the only user on my system but some services use other user accounts:

![image](https://user-images.githubusercontent.com/8304331/94011530-cbdf5b80-fda7-11ea-823d-06b7ff858567.png)

**Comment by don-dolarson** [comment]
Trust me. I know my machine who no one else even touch. I'm the only one user.

**Comment by kadrim** [comment]
i am not talking of physical users. Every windows 10 has at least 3 service users:

"Localservice"
"Networkservice"
"SYSTEM"

Could you please use the windows taskmanager, switch to the "Details" Tab and make a screenshot of the row containing the Mbamservice.exe

if the need arises, i will also setup a virtual machine with that service to double check the problem.

**Comment by don-dolarson** [comment]
Alright, you mean that.

![MBAMService exe](https://user-images.githubusercontent.com/49354563/94264487-16431280-ff37-11ea-8b97-6e97027bb39b.jpg)

Here's the software:
https://www.malwarebytes.com/

**Comment by kadrim** [comment]
thanks for your reply. so the .exe is runnung as the user "SYSTEM" as i expected. that should not be a problem as we do the UAC but as it is an antivirus software it might prevent other applications from reading the footprint.

i will test this issue on a virtual machine this weekend and share my insights.

**Comment by don-dolarson** [comment]
Did you check it?

**Comment by kadrim** [comment]
yes, i did check it and also got the error, that the program is trying to read a non-accessible variable.

the mbamservice.exe is preventing itself from being read out - maybe as a threat-protection.
it even does so, if i add my program to the exclusion list. 

so i have to use another workaround to read the memory footprint - i already have found a suitable way, but must implement it.

**Comment by kadrim** [comment]
I think the solution for your issue is to use Version 0.0.3

Within that version, there was another way to get the memory footprint of almost anything. But it lead to memory leaks on windows XP.
As you are using windows 10, this should not be an issue.

Simply download 0.0.3 and try it out. the feature set for 0.0.3 and 0.0.4 is identical.

**Comment by kadrim** [comment]
https://github.com/kadrim/PrimoCacheBackupDetect/releases/tag/v0.0.3

**Comment by kadrim** [comment]
Did this work for you?

**Comment by don-dolarson** [comment]
Sorry for not testing it yet. I'm on holiday until Monday. Will test it next week and report back, probably Tuesday.

**Comment by kadrim** [comment]
any news? does it work it for you and can i close this issue?

**Comment by don-dolarson** [comment]
I'm so sorry for the delay. Completely forgot about this, and I've had other things to do.
However, I've just checked the 0.0.3 version and it works flawlessly with MBAMService.exe :)

Thank you.

**Comment by kadrim** [comment]
Thanks for your reply and the testing you have done :-)

i will close the issue now
